site_name: Reusable CI/CD
site_url: https://reusable-cicd.automationdojo.org
repo_url: https://github.com/AutomationDojo/reusable-cicd

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - search.highlight

plugins:
  - search

nav:
  - Home: index.md
  - Actions:
      - Helm Repo Init: actions/helm-repo-init.md
      - ArgoCD Diff Preview: actions/argocd-diff-preview.md
  - Workflows:
      - Actionlint: workflows/actionlint.md
      - Cloudflare Pages Cleanup: workflows/cloudflare-pages-cleanup.md
      - Golang CLI Build and Test: workflows/golang-cli-build-and-test.md
      - Golang CLI Release: workflows/golang-cli-release.md
      - MkDocs Deploy: workflows/mkdocs-deploy.md
      - MkDocs + Helm Pages: workflows/mkdoc-helm_deploy.md
      - Node Build and Test: workflows/node-build-and-test.md
      - Node Release: workflows/node-release.md
      - Simple Semantic Release: workflows/semantic-release-simple.md
      - Terraform Docs: workflows/terraform-docs.md
      - Helm Lint: workflows/helm-lint.md
      - Helm Docs: workflows/helm-docs.md
      - Helm Releaser: workflows/helm-releaser.md
      - Docker Build and Push: workflows/docker-build-push.md
      - ArgoCD Diff Preview: workflows/argocd-diff-preview.md